# bundle exec jekyll serve --livereload

# General settings
title: "@kastney"
favicon: "/assets/images/favicon.ico"

# Language settings
lang: "pt-br"

# Styles settings
sass:
  style: compressed

# Markdown settings
kramdown:
  input: kramdown
  
# Plugins settings
plugins:
  - jekyll-timeago
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship
  - jekyll-paginate-v2
  - jekyll-scholar