# bundle exec jekyll serve --livereload

# General settings
favicon: "/assets/images/favicon.ico"

# Language settings
languages: [ "br", "us" ]
translations: [ "br", "us" ]
exclude_from_localizations: [ "assets" ]

# Collections settings
collections_dir: _collections
collections:
  certificates_br:
    output: true
  certificates_us:
    output: true

# Paginate settings
pagination:
  enabled: true
  debug: false
  permalink: '/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Markdown settings
kramdown:
  input: kramdown

# Optimization settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: true
  profile: false
  startings: [html, head, body]
sass:
  style: compressed
  
# Plugins settings
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate-v2
  #- jekyll-timeago
  #- jekyll-feed
  #- jekyll-seo-tag
  #- jekyll-sitemap
  #- jekyll-spaceship
  #- jekyll-scholar