# bundle exec jekyll serve --livereload

# General settings
title: '@kastney'

# Language settings
language: pt

# Fav Icon settings
favicon: '/assets/images/favicon.png'

# Collections settings
collections_dir: _collections
collections:
  blog:
    output: true
    permalink: /blog/:name/
  games:
    output: true
    permalink: /games/:name/

# Pagination setting
pagination:
  enabled: true
  debug: false
  permalink: '/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: kramdown
kmarkdown:
  input: GFM

# Pluging settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship
  - jekyll-paginate-v2