# bundle exec jekyll serve --livereload

title: "Jekyll Actions Demo"

plugins:
  - jekyll-timeago
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship
  - jekyll-paginate-v2
  - jekyll-scholar