# bundle exec jekyll serve --livereload

# Language settings
lang: "pt-br"

# Plugins settings
plugins:
  - jekyll-timeago
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship
  - jekyll-paginate-v2
  - jekyll-scholar