# bundle exec jekyll serve --livereload

# General settings
title: "kastney"
favicon: "/assets/images/favicon.ico"

# Language settings
languages: [ "pt", "en" ]
exclude_from_localizations: [ "assets" ]

# Markdown settings
kramdown:
  input: kramdown

# Optimization settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: true
  profile: false
  startings: [html, head, body]
sass:
  style: compressed
  
# Plugins settings
plugins:
  - jekyll-multiple-languages-plugin
  #- jekyll-timeago      #*
  #- jekyll-feed         #*
  #- jekyll-seo-tag      #*
  #- jekyll-sitemap      #*
  #- jekyll-spaceship    #*
  #- jekyll-paginate-v2  #*
  #- jekyll-scholar      #*